### ISSUE TITLE
Watch window showing null when variable isn't null!

### ISSUE THREAD

**Issue by dazinator** [xamarin/Xamarin.VSSDK#18]
Not sure if I am raising this in the correct place.

I am not sure this issue is to do with EF or something else.

I am debugging an app that targets `monodroid80` using VS2017 version `15.4.4` and witnessing some strange behaviour with variables in the watch windows.

For example, when I do the following:

```
                var items = visit.Callfile.Survey.SurveyItems.ToList();
                var itemsWithWhere = visit.Callfile.Survey.SurveyItems.Where((a) => true).ToList();
                var orderedSurveyItems = visit.Callfile.Survey.SurveyItems.Where((x) => {
                    return true;
                }).ToList();

```
Result in watch window are:

`items` contains 1 result.
`itemsWithWhere` contains 1 result.
`orderedSurveyItems` (forgive the name as I know there is no "order by" there) shows as: (null).

I can witness as the prgram executes, that the variable is not really null - the watch windows just reports it as such.

Here is a picture at a breakpoint showing the state of these three variables:

![image](https://user-images.githubusercontent.com/3176632/32837495-b3102fcc-ca05-11e7-98ea-d79994339877.png)

If I rename the variable from `orderedSurveyItems` to `fooVariable` - and then re-run the program, it then fixes it - fooVariable shows in the watch window with 1 result as expected. Renaming the variable back to `orderedSurveyItems` - and the watch window shows it as `null` again.

My code is executing within an async task - and it appears to be the same problem as described here: 
https://stackoverflow.com/questions/37411105/visual-studio-2015-debugger-showing-null-when-object-is-not-null

The only thing special about the variable name `orderedSurveyItems` that I can see is that the same variable name is also used for a private method which is called later:

```
 private void PerformCalculations(CallfileVisit visit
            , int surveyItemGroupId
            , IEnumerable<SurveyItem> orderedSurveyItems
            , IList<SurveyItemResponse> surveyItemResponses
            , out int totalNumberOfSurveyItemHaveResponse
            , out int totalNumberOfSurveyItemSkipped)
        {
``` 

It's almost as if the watch window is showing the wrong one. When execution enters the above private method, suddenly the watch windows shows `orderedSurveyItems` as having 1 item. When execution returns to the calling method, `orderedSurveyItems` shows as null again.

The signature of the method containing this code is as follows:

```
public async Task<Tuple<IEnumerable<ISurveyItemGroupModel>, bool>> GetSurveyItemGroupsAsync(int visitId)
```

Not a nice signature in terms of readability, I know.

Operating system: Windows 10
IDE: Visual Studio 2017 15.4.4

Is there somewhere else I should be raising this issue?

**Comment by kzu** [comment]
Closing. This is just for VS extensibility authors.

**Comment by dazinator** [comment]
Ok. Is the xamarin mono debugger not a VS extension point? Apologies. I'll try and rause this through vs report an issue instead!

**Comment by kzu** [comment]
Sorry about the confusion of repositories. If you are consuming the Xamarin
toold for Visual Studio, the "Send Feedback" inside VS is the most
appropriate way to reach us, yes. We actively monitor it.

Thanks!
-- 

--
/kzu from mobile
